// <auto-generated />
namespace UpdateManager.Web.DataContexts.UpdatesMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class AddedSemVerSupport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedSemVerSupport));
        
        string IMigrationMetadata.Id
        {
            get { return "201312160518424_AddedSemVerSupport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
